config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :edit, :update, :show, :new, :create, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#                    Prefix Verb   URI Pattern                         Controller#Action
#                  root GET    /                                            homes#top
#                 about GET    /homes/about(.:format)                       homes#about
#      new_user_session GET    /users/sign_in(.:format)            devise/sessions#new
#          user_session POST   /users/sign_in(.:format)           devise/sessions#create
#  destroy_user_session DELETE /users/sign_out(.:format)          devise/sessions#destroy
# new_user_registration GET    /users/sign_up(.:format)      devise/registrations#new
#edit_user_registration GET    /users/edit(.:format)         devise/registrations#edit
#     user_registration PATCH  /users(.:format)              devise/registrations#update
#                       PUT    /users(.:format)              devise/registrations#update
#                       DELETE /users(.:format)              devise/registrations#destroy
#                       POST   /users(.:format)              devise/registrations#create
#                 books GET    /books(.:format)                             books#index
#                       POST   /books(.:format)                             books#create
#              new_book GET    /books/new(.:format)                         books#new
#             edit_book GET    /books/:id/edit(.:format)                    books#edit
#                  book GET    /books/:id(.:format)                         books#show
#                       DELETE /books/:id(.:format)                         books#destroy
#                       PATCH  /books/:id(.:format)                         books#update
#                       PUT    /books/:id(.:format)                         books#update

#                 users GET    /users(.:format)                             users#index
#             edit_user GET    /users/:id/edit(.:format)                    users#edit
#                  user GET    /users/:id(.:format)                         users#show
#                       PATCH  /users/:id(.:format)                         users#update
#                       PUT    /users/:id(.:format)                         users#update

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] ="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])  #ローカル変数→インスタンス変数。renderのため。
    if @book.update(book_params)
      flash[:notice] ="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @book = Book.new
    if current_user && params[:id] == current_user.id.to_s
      @user = current_user
      @books = @user.books
    else params[:id]
      @user = User.find(params[:id])
      @books = @user.books
    end

  end

  def edit
    # if params[:id] == current_user.id.to_s
      @user = User.find(params[:id])
    # else
      # redirect_to user_path(params[:id])
    # end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


private

def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">

      <% if @book.errors.any? %>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <div>
        <h1>Editing Book</h1>
        <%= form_with model: @book do |f| %>
          <div>
            <label for="inputTitle">Title</label>
          </div>
          <div>
            <%= f.text_field :title, autofocus: true, id:"inputTitle" %>
          </div>
          <div>
            <label for="inputOpinion">Opinion</label>
          </div>
          <div>
            <%= f.text_field :body, autofocus: true, id:"inputBody" %>
          </div>
            <%= f.submit "Update Book", class:"btn btn-success" %>
        <% end %>
      </div>

      <div>
        <%= link_to "Show", book_path(params[:id]) %>
        <a>|</a>
        <%= link_to "Back", books_path %>
      </div>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

    <% if @book.errors.any? %>
      <%= @book.errors.count %> errors prohibited this obj from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
       <% end %>
      </ul>
    <% end %>

  <div class="row">

    <div class="col-md-3">
      <%= render 'users/userbook', book: @book, user: @user %>
    </div>


    <div class="col-md-8 offset-md-1">

      <div>
        <h2>Books</h2>
        <table class="table tablehover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th class="colspan=3"></th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id), class:"link-primary" do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>


  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">


    <div class="col-md-3">
      <%= render 'users/userbook', book: @book_new, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user_id) do %>
               <%= image_tag @book.user.get_profile_image(100,100) %>
                <br><%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book.id), class: "button btn-sm btn-success" %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Destroy", @book, class: "button btn-sm btn-danger", method: :delete,
                             "data-confirm" => "本当に消しますか？" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/homes/_topflash.html.erb
<% flash.each do |key, value| %>
  <div class="flash-<%= key %>">
    <%= value %>
  </div>
<% end %>

<!--Logout後メッセージとしてtopに %= render 'topflash' %を記載しようと思ったが、不要（自動）-->

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 py-3 mx-auto">
      <h1>Welcome to
        <i class="fa-solid fa-book"></i>
        <strong>Bookers</strong>
      !</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<!--%= flash[:notice] %>-->

<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>welcome to
      <i class="fa-solid fa-book"></i>
      <strong class="fw-bold">Bookers</strong>
      !!</h1>
      <div></div>
      <p>In
      <i class="fa-solid fa-book"></i>
      <strong class="fw-bolder">Bookers</strong>
      ,</p>
      <p>
        you can share and exchange your opinions , inpressions ,
        and emotions
      </p>
      <p>about various books!</p>

      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to new_user_session_path, class: "btn btn-info", autocomplete:"off" do %>
          <span>Log in</span>
        <% end %>
        <%= link_to new_user_registration_path, class: "btn btn-success", autocomplete:'off' do %>
          <span>Sign up</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/18d078742a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body class="flex-colum vh-100">
    <header class="bg-dark text-light">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand" href= "<%= root_path %>">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'btn btn-default text-light' do %>
                  <i class="fa-solid fa-house"></i>
                  <span>Home</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'btn btn-default text-light' do %>
                  <i class="fa-solid fa-users"></i>
                  <span>Users</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'btn btn-default text-light' do %>
                  <i class="fa-solid fa-book-open"></i>
                  <span>Books</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, class: 'btn btn-default text-light', method: :delete do %>
                  <i class="fa-solid fa-right-from-bracket"></i>
                  <span>Log out</span>
                <% end %>
              </li>

              <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'btn btn-default text-light link-body-emphasis' do %>
                  <i class="fa-solid fa-house"></i>
                  <span>Home</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path, class: 'btn btn-default text-light' do %>
                  <i class="fa-solid fa-link"></i>
                  <span>About</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'btn btn-default text-light' do %>
                  <i class="fa-solid fa-user-plus"></i>
                  <span>Sign up</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'btn btn-default text-light' do %>
                  <i class="fa-solid fa-right-to-bracket"></i>
                  <span>Log in</span>
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>

    <footer class="mt-5 bg-white text-black pt-3 pb-5">
      <div class="container">
        <div class="row">
          <div class="mx-auto"><p>CopyRight Infratop.inc</p></div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_userbook.html.erb
<div>
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <thead>
      <tr>
        <th style="border-bottom:1px">name</th>
        <th style="border-bottom:1px"><%= user.name %></th>
      </tr>
      <tr>
        <th style="border-bottom:none">introduction</th>
        <th style="border-bottom:none"><%= user.introduction %></th>
      </tr>
    </thead>
  </table>
  <div>
    <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block' do %>
      <i class="fa-solid fa-user-gear"></i>
    <% end %>
  </div>
</div>

<div>
  <h2 class="mt-3">New book</h2>
  <%=form_with model: book do |f| %>
  <div class="form">
    <label for="inputTitle">Title</label>
    <div><%= f.text_field :title, class:"form-control" %></div>
    <label for="inputOpinion">Opinion</label>
    <div><%= f.text_area :body, class:"form-control", rows:"3" %></div>
    <%= f.submit 'Create Book', class:"btn btn-success mt-3" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">

      <% if @user.errors.any? %>
        <%= @user.errors.count %> errors prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <div>
        <h1>User info</h1>
        <%= form_with model: @user do |f| %>
          <div>
            <label for="inputName">Name</label>
          </div>
          <div>
            <%= f.text_field :name, autofocus: true, id:"inputName" %>
          </div>
          <div>
            <label for="inputImage">Image</label>
          </div>
          <div>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>
          <div>
            <label for="inputIntroduction">Introduction</label>
          <div>
            <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>
          </div>
            <%= f.submit "Update User", class:"btn btn-secondary" %>
        <% end %>
      </div>

      <div>
        <%= link_to "Show", book_path(params[:id]) %>
        <a>|</a>
        <%= link_to "Back", books_path %>
      </div>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <%= render 'userbook', user: current_user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">

      <div>
        <h1>Users</h1>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">image</th>
              <th scope="col">name</th>
              <th></th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    <div>


  </div>
</div>

app/views/users/show.html.erb
<!--%= flash[:notice] %-->

<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

    <div class="col-md-3">
      <%= render 'userbook', book: @book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th class="colspan=3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(params[:id]) do %>
                <%= image_tag book.user.get_profile_image(100,100) %></td>
              <% end %>
            <td>
              <%= link_to book_path(book.id), class:"link-primary" do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>